import React from 'react';
import { motion } from 'framer-motion';
import { formatters } from '../../utils/formatters';

const ClaimCard = ({ claim }) => {
  const getClaimIcon = (type) => {
    const icons = {
      rain_disruption: '🌧️',
      heat_wave: '🔥',
      air_pollution: '😷',
      storm: '⛈️',
      flood: '🌊',
      accident: '🚗',
      medical: '🏥'
    };
    return icons[type] || '📋';
  };

  const getStatusColor = (status) => {
    switch(status) {
      case 'approved': return 'bg-green-100 text-green-800';
      case 'pending': return 'bg-yellow-100 text-yellow-800';
      case 'processing': return 'bg-blue-100 text-blue-800';
      case 'rejected': return 'bg-red-100 text-red-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  const getStatusIcon = (status) => {
    switch(status) {
      case 'approved': return '✅';
      case 'pending': return '⏳';
      case 'processing': return '⚙️';
      case 'rejected': return '❌';
      default: return '📋';
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="bg-white rounded-2xl shadow-lg p-6 hover:shadow-xl transition"
    >
      <div className="flex items-start justify-between">
        <div className="flex items-center space-x-4">
          <div className="w-12 h-12 bg-gradient-to-r from-blue-500 to-purple-500 rounded-full flex items-center justify-center text-2xl">
            {getClaimIcon(claim.type)}
          </div>
          <div>
            <h3 className="text-lg font-semibold text-gray-900 capitalize">
              {claim.type?.replace('_', ' ') || 'Manual Claim'}
            </h3>
            <p className="text-sm text-gray-500">Claim #{claim.claimNumber?.slice(-8)}</p>
          </div>
        </div>
        <div className={`px-3 py-1 rounded-full text-sm font-semibold ${getStatusColor(claim.status)}`}>
          {getStatusIcon(claim.status)} {claim.status.toUpperCase()}
        </div>
      </div>

      <div className="mt-4 grid grid-cols-2 md:grid-cols-4 gap-4">
        <div>
          <p className="text-xs text-gray-500">Amount</p>
          <p className="text-xl font-bold text-gray-900">₹{claim.amount}</p>
        </div>
        <div>
          <p className="text-xs text-gray-500">Submitted</p>
          <p className="text-sm text-gray-700">{formatters.date(claim.createdAt)}</p>
        </div>
        {claim.processedAt && (
          <div>
            <p className="text-xs text-gray-500">Processed</p>
            <p className="text-sm text-gray-700">{formatters.date(claim.processedAt)}</p>
          </div>
        )}
        <div>
          <p className="text-xs text-gray-500">Policy</p>
          <p className="text-sm text-gray-700 capitalize">{claim.policyId?.planType} Shield</p>
        </div>
      </div>

      {claim.description && (
        <div className="mt-4 p-3 bg-gray-50 rounded-lg">
          <p className="text-sm text-gray-600">{claim.description}</p>
        </div>
      )}

      {claim.status === 'approved' && (
        <div className="mt-4 p-3 bg-green-50 rounded-lg flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <span className="text-green-600">✓</span>
            <span className="text-sm text-green-800">Claim approved! Amount will be credited within 24 hours.</span>
          </div>
          <button className="text-sm text-green-600 hover:text-green-700 font-medium">
            Track Payment →
          </button>
        </div>
      )}

      {claim.disruptionData && (
        <div className="mt-3 text-xs text-gray-500">
          🤖 Auto-generated by AI trigger
        </div>
      )}
    </motion.div>
  );
};

export default ClaimCard;